# Page settings
baseURL = "https://cv.julienklaer.dev/"
languageCode = "en-us"
title = "Curriculum Vitae - Julien Klaer"
theme = "hugo-devresume-theme"

[params]
    author = "Julien Klaer"
    description = "Curriculum Vitae - Julien Klaer"
    primaryColor = "#54B689"
    textPrimaryColor = "#292929"

    [params.profile]
        enable = true
        name = "Julien Klaer ☁️"
        tagline = "Senior Software Engineer - Cloud Architect"
        avatar = "me.png"

    [params.contact]
        enable = true
        location = "Luxembourg"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:0033669563463"
        text = "+33 6 69 56 34 63"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:klaer.julien@gmail.com"
        text = "klaer.julien@gmail.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "https://www.julienklaer.dev"
        text = "julienklaer.dev"

    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical skills"
        [[params.skills.list.items]]
        details = "Java - Golang - Python"
        [[params.skills.list.items]]
        details = "JavaScript - TypeScript"
        [[params.skills.list.items]]
        details = "SpringBoot - Flask - FastAPI - Angular"
        [[params.skills.list.items]]
        details = "PostgreSQL - MongoDB - Datastore - Firestore"
        [[params.skills.list.items]]
        details = "Apache Kafka - Pub/Sub"
        [[params.skills.list.items]]
        details = "GitHub Actions - Cloud Build - Jenkins"
        [[params.skills.list.items]]
        details = "Istio - Knative - Kubernetes - Docker/containerd"
        [[params.skills.list.items]]
        details = "Google Cloud Platform - SysAdmin *general* skills"

        [[params.skills.list]]
        title = "Soft skills"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Passionate"
        [[params.skills.list.items]]
        details = "Entrepreneurship"

    [params.education]
        enable = true

        [[params.education.list]]
        degree = "Computer science degree"
        university = "Université de Lorraine, Metz, France"
        dates = "2014"
        [[params.education.list]]
        degree = "University technological diploma"
        university = "Université de Lorraine, Metz, France"
        dates = "2012"
        [[params.education.list]]
        degree = "Scientist Bachelor"
        university = "Lycée Condorcet, Schoeneck, France"
        dates = "2010"

    [params.awards]
        enable = true

        [[params.awards.list]]
        name = "Certified Kubernetes Administrator"
        body = "Cloud Native Computing Foundation"
        date = "2019"
        url = "https://www.youracclaim.com/badges/d4555572-52f2-4767-9227-6dfb88006fce"
        [[params.awards.list]]
        name = "Google Cloud Certified"
        body = "Professional Cloud Architect"
        date = "2018"
        url = "https://www.credential.net/f2228374-66be-49d1-a5fb-63a3914f8adf?key=070697e1271dac232dc7b545e153a5ea49a921c302a9f06a1bab89dd47e61ab3"

    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "French"
        level = "Native"
        [[params.languages.list]]
        name = "English"
        level = "Professional"
        [[params.languages.list]]
        name = "German"
        level = "Proficient"

    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Music 🎵 🎸"
        [[params.interests.list]]
        name = "Riding Motorcycle 🏍️"
        [[params.interests.list]]
        name = "Video Games 🕹️"
        [[params.interests.list]]
        name = "Computer Science 🤓"

    [params.summary]
        enable = true
        text = '''I am a Senior Software Engineer that got caught in the wonderful world of Cloud Computing and DevOps philosophy. Always eager to learn new things, I like putting time in technology watch to find out what are the last trends! Lastly, I've put some effort on learning Python and Golang which I just fell in love with ❤️   
        I love challenges and meet new people. I am conviced that everyone has a story and something to share! 🧑‍🤝‍🧑   
        Last but not least, despite being sensitive to pressure, I am always doing my best to share my good vibes! 🌊'''

    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Lead Software Engineer - Cloud Architect"
        dates = "September 2020 - Present"
        company = "Next Gate Tech"
        details = "Next Gate Tech is a FinTech that provides innovative SaaS solutions for the asset management industry. As a Cloud based company, I worked there first as a Google Cloud Architect and earned further responsibilites as Lead of the Software Engineer team. As such, I was commited to numerous projects which are mostly written using Python."
        
        [[params.experience.list.items]]
        details = """maintainance and putting in place **best practices** around consumption of the **Google Cloud Platform**.
        (Cloud Functions, Cloud Run, AppEngine, Compute Engine, Cloud Storage, Pub/Sub, BigQuery, Firestore/Datastore, Cloud Operation)"""
        
        [[params.experience.list.items]]
        details = "responsible of managing the **costs** around the **Google Cloud Platform** (alerts, reports)"
        
        [[params.experience.list.items]]
        details = "entire **migration** of the company information system to a more central place: **Google Workspace**"
       
        [[params.experience.list.items]]
        details = """responsible of managing the company information system to assure **best security practices** (password length, 2FA),
         applications (drive, doc, ...) and entities (user, groups)"""

        [[params.experience.list.items]]
        details = "**administrator of the domain**, managing DNS rules (e.g. SPF, DKIM, DMARC)"

        [[params.experience.list.items]]
        details = "**development and maintainance** of Next Gate Tech first solution in Python 3.7 🐍 (scalable, cost efficient and reliable data pipelines)"

        [[params.experience.list.items]]
        details = "development of a new version of Next Gate Tech solution that is **cloud independant** (project NGX) in Python 3.9 🐍"

        [[params.experience.list.items]]
        details = "responsible of deploying the new NGX stack to a **new Cloud provider (IBM Cloud)** for one of the client's needs"

        [[params.experience.list.items]]
        details = "**project management** on part of the NGX project following the agile methodology"

        [[params.experience.list.items]]
        details = "promoting a **DevOps philosophy** by putting in place tools like **Infrastructure as Code** (Terraform) or **CI/CD** (GitHub Actions/Cloud Build)"

        [[params.experience.list.items]]
        details = "reviewing security policies written by the **Cybersecurity Engineer** and writting procedure and documentation around systems availability using SRE (BCP, DRP, ...)"

        [[params.experience.list.items]]
        details = "ensuring healthy systems to meet business satisfaction"

        [[params.experience.list.items]]
        details = "**manage** all software engineers of the company"


        [[params.experience.list]]
        title = "Consultant DevOps Engineer"
        dates = "March 2020 - September 2020"
        company = "RBC Investor & Treasury Services for SFEIR"
        details = "Helping developers to deliver more business value by providing them tools, support and help migrating applications to modern technologies like OpenShift, Pivotal Cloud Foundry, [...] Also in charge of providing services to developers like CI/CD, workflow pipelines, server provisioning..."

        [[params.experience.list]]
        title = "Consultant Cloud Architect"
        dates = "January 2020 - February 2020"
        company = "SFEIR"
        details = "Small mission for helping some of my colleagues at Sfeir to migrate one of our client from Amazon AWS to Google Cloud Platform (GCP). I have put in place their workload in a fully managed GKE. (Google Kubernetes Engine)"
        [[params.experience.list.items]]
        details = "Google Kubernetes Engine"
        [[params.experience.list.items]]
        details = "Cloud Build | Container Registry"
        [[params.experience.list.items]]
        details = "Java/SpringBoot | Angular/TypeScript"

        [[params.experience.list]]
        title = "Consultant DevOps Engineer - Java Developer"
        dates = "October 2018 - March 2020"
        company = "ING Luxembourg for SFEIR"
        details = "Aware of their change and run problems, ING has a big objective of developing their infrastructure and processes. To let teams be more autonomous and manage releases and incidents linked to their assets, ING entrusted me with the creation of an OPS unit and the deployment of the movement. This action is initiated by the Tribe Daily Banking & Lending Engine and extended to all the bank's services. Apart from that, I have been working for a huge migration project at ING Luxembourg that completely refactor the existing payment processing thanks to my Java seniority."
        [[params.experience.list.items]]
        details = "Set up a guild dedicated to the movement, to spread the DevOps culture within ING."
        [[params.experience.list.items]]
        details = "Implementing tools such as Jenkins for packaging, Ansible for infrastructure as code, ELK (Elasticsearch, Logstash, Kibana) for logs aggregation and service liveness."
        [[params.experience.list.items]]
        details = "Evangelization of the DevOps model and implementation of the strategy."
        [[params.experience.list.items]]
        details = "Helping on development of the PSD2 European directive."
        [[params.experience.list.items]]
        details = "Huge migration of the SWIFT payment platform to the ING group payment platform that runs thousands of daily payments."
        
        [[params.experience.list]]
        title = "Consultant Fullstack Developer"
        dates = "May 2017 - October 2018"
        company = "Société Générale Bank and Trust for SFEIR"
        details = "Migration of a legacy trading application made in Java QT Jambi for the frontend with Spring 3 backend applications. We have been migrating one financial product at a time from a monolithic perspective into microservices and micro frontends applications using Spring Boot 2 and Angular 6.I wrote a complete Groovy framework for our needs using Jenkinsfile for pipeline as code. We used XLDeploy from XebiaLabs to deploy applications in our environments. I have propagated the idea of using Docker by providing them a proof of concept of the technology. Also, I have developed a complete CI/CD pipeline for Angular application since no native solution for building and packaging components libraries were existing at this time."
        [[params.experience.list.items]]
        details = "Migration of a legacy trading application written in Java QT Jambi into a brand-new web application made with Spring Boot | Angular."
        [[params.experience.list.items]]
        details = "Guiding and building some continuous delivery system for both Java and JavaScript technology (compilation, test, release, publishing, deployment) using Groovy, Jenkins pipeline (infrastructure as code) and writing a shared library."
        [[params.experience.list.items]]
        details = "Advising transversal architecture team about how to use Docker and doing some POC with Spring Cloud integration."

        [[params.experience.list]]
        title = "Consultant Fullstack Developer"
        dates = "February 2017 - May 2017"
        company = "Legitech for SFEIR"
        details = "Development of a document management platform used by jurists and lawyers to aggregate laws to make them more readable and user friendly. I was assigned the task of developing the desktop publishing application to print consolidated rules as books."
        [[params.experience.list.items]]
        details = "Development of a DTP (desktop publishing) application in order to manipulate legal text. (consolidation, reference, reordering, ...)"
        [[params.experience.list.items]]
        details = "Extraction of this consolidated data and transformation into a specific format intended to be released by a printer-publisher."
        
        [[params.experience.list]]
        title = "Team Leader - Consultant Software Enginneer - Trainer"
        dates = "February 2017 - September 2020"
        company = "SFEIR"
        details = "I joined SFEIR as an fullstack IT engineer specialized in backend, DevOps and Cloud Computing. Shortly after joining I became quickly important by being granted responsibilities of coaching collegues that were spreaded across different clients. Also, I was responsible of training people on subjects like Docker or Kubernetes. Among all of this, I played my role as a recruiter and gave several talk on trending subjects (IoT, Golang, ...)"
        [[params.experience.list.items]]
        details = '''As a Team Leader I was:

        coaching and managing a team of 10 people

        following the career of each of my collegues and their mission

        meeting clients to measure their happiness regarding what we delivered to them

        planning an end of year interview with collegues discussing career and salary package
        '''
        [[params.experience.list.items]]
        details = '''As a Trainer I was:
        
        creating new support (slides, exercices) like the Docker and Kubernetes one
        
        giving basic and advanced training courses / talk for internal people and for clients
        like the Deputy Chamber in Luxembourg or even the CSSF
        
        giving complete training sessions espectially made for clients like Alten in Switzerland'''
        [[params.experience.list.items]]
        details = '''As a Recruiter I was:
        
        Helping Talent Managers recriot new people for our company in coding sessions
        that we called PlayOff. Playoffs are composed of three practial tests (live coding)
        that touches algorithms, languages and platforms (frameworks)
        
        With Playoffs we were able to assess both people technical and soft skills.'''

        [[params.experience.list]]
        title = "Analyst Programmer"
        dates = "September 2016 - February 2017"
        company = "PwC Luxembourg"
        details = "Working for the TMA team, I was assigned the task to restore Java application stability in production and modernize those applications."
        [[params.experience.list.items]]
        details = "Ensure the quality and the availability of many applications"
        [[params.experience.list.items]]
        details = "Set up new tools to facilitate maintenance"
        [[params.experience.list.items]]
        details = "Analysis of day-to-day problems and work to find solutions"
        [[params.experience.list.items]]
        details = "Modernize existing applications"

        [[params.experience.list]]
        title = "System Administrator"
        dates = "July 2014 - September 2016"
        company = "efluid SAS"
        details = "Junior system administrator/integrator inside the process of fabrication team led by Thomas Collignon. In charge of design, development and testing in the field of automation applications in manufacturing processes. Implementation of recurrent tasks process (automatic compilations, nightly builds, continuous integration, packaging, deployment)."
        [[params.experience.list.items]]
        details = "Responsible of the release management of applications"
        [[params.experience.list.items]]
        details = "Ensuring that the continuous integrations and health of the applications are stable"
        [[params.experience.list.items]]
        details = "Supervise deployed applications in development, test, and QA environments"
        [[params.experience.list.items]]
        details = "Participating to the improvement of our tools to implement our DevOps strategy (Docker, Jenkins pipeline, Groovy)"
        [[params.experience.list.items]]
        details = "training people for Git SCM"


    [params.projects]
        enable = false

        [[params.projects.list]]
        title = "Project Lorem Ipsum"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.projects.list]]
        title = "Project Sed Fringilla"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

        [[params.projects.list]]
        title = "Project Praesent"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

    [params.information]
        enable = false

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Climbing, Snowboarding, Photography, Travelling"

    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/MadJlzz"
        title = "MadJlzz"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/klaer-julien"
        title = "Julien Klaer"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "//twitter.com/MadJlzz"
        title = "@MadJlzz"
