# Page settings
baseURL = "https://cv.julienklaer.dev/"
languageCode = "en-us"
title = "Curriculum Vitae - Julien Klaer"
theme = "hugo-devresume-theme"

[params]
    author = "Julien Klaer"
    description = "Curriculum Vitae - Julien Klaer"
    primaryColor = "#54B689"
    textPrimaryColor = "#292929"

    [params.profile]
        enable = true
        name = "Julien Klaer"
        tagline = "Senior Software Engineer - Cloud Architect"
        avatar = "avatar.png"

    [params.contact]
        enable = true
        location = "Luxembourg"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:0033669563463"
        text = "+33 6 69 56 34 63"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:klaer.julien@gmail.com"
        text = "klaer.julien@gmail.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "https://www.julienklaer.dev"
        text = "julienklaer.dev"

    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical skills"
        [[params.skills.list.items]]
        details = "Java | Golang | Python"
        [[params.skills.list.items]]
        details = "JavaScript | TypeScript"
        [[params.skills.list.items]]
        details = "SpringBoot | Flask | Angular"
        [[params.skills.list.items]]
        details = "SQL | NoSQL like Oracle/Firestore"
        [[params.skills.list.items]]
        details = "AMQP like PubSub/Apache Kafka"
        [[params.skills.list.items]]
        details = "GitHub Actions | Jenkins"
        [[params.skills.list.items]]
        details = "Istio | Kubernetes | Docker/containerd"
        [[params.skills.list.items]]
        details = "Google Cloud Platform | SysAdmin 'general' skills"

        [[params.skills.list]]
        title = "Soft skills"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Entrepreneurship"

    [params.education]
        enable = true

        [[params.education.list]]
        degree = "Computer science degree"
        university = "Université de Lorraine, Metz, France"
        dates = "2014"
        [[params.education.list]]
        degree = "University technological diploma"
        university = "Université de Lorraine, Metz, France"
        dates = "2012"
        [[params.education.list]]
        degree = "Scientist Bachelor"
        university = "Lycée Condorcet, Schoeneck, France"
        dates = "2010"

    [params.awards]
        enable = true

        [[params.awards.list]]
        name = "Certified Kubernetes Administrator"
        body = "Cloud Native Computing Foundation"
        date = "2019"
        url = "https://www.youracclaim.com/badges/d4555572-52f2-4767-9227-6dfb88006fce"
        [[params.awards.list]]
        name = "Google Cloud Certified"
        body = "Professional Cloud Architect"
        date = "2018"
        url = "https://www.credential.net/f2228374-66be-49d1-a5fb-63a3914f8adf?key=070697e1271dac232dc7b545e153a5ea49a921c302a9f06a1bab89dd47e61ab3"

    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "French"
        level = "Native"
        [[params.languages.list]]
        name = "English"
        level = "Professional"
        [[params.languages.list]]
        name = "German"
        level = "Proficient"

    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Music 🎵 🎸"
        [[params.interests.list]]
        name = "Riding Motorcycle 🏍️"
        [[params.interests.list]]
        name = "Video Games 🕹️"
        [[params.interests.list]]
        name = "Computer Science 🤓"

    [params.summary]
        enable = true
        text = "Summarise your career here. Donec quam felis, ultricies nec, pellentesque eu. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.  Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh."

    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Lead Software Engineer - Cloud ☁️ Architect"
        dates = "September 2020 - Present"
        company = "Next Gate Tech"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis."
        [[params.experience.list.items]]
        details = "Lorem ipsum dolor sit amet, consectetuer."
        [[params.experience.list.items]]
        details = "Aenean commodo ligula eget dolor."
        [[params.experience.list.items]]
        details = "Etiam ultricies nisi vel augue."

        [[params.experience.list]]
        title = "Consultant DevOps Engineer"
        dates = "March 2020 - September 2020"
        company = "RBC Investor & Treasury Services"
        details = "Helping developers to deliver more business value by providing them tools, support and help migrating applications to modern technologies like OpenShift, Pivotal Cloud Foundry, [...] Also in charge of providing services to developers like CI/CD, workflow pipelines, server provisioning..."

        [[params.experience.list]]
        title = "Consultant Cloud Architect"
        dates = "January 2020 - February 2020"
        company = "SFEIR"
        details = "Small mission for helping some of my colleagues at Sfeir to migrate one of our client from Amazon AWS to Google Cloud Platform (GCP). I have put in place their workload in a fully managed GKE. (Google Kubernetes Engine)"
        [[params.experience.list.items]]
        details = "Google Kubernetes Engine"
        [[params.experience.list.items]]
        details = "Cloud Build | Container Registry"
        [[params.experience.list.items]]
        details = "Java/SpringBoot | Angular/TypeScript"

        [[params.experience.list]]
        title = "Consultant DevOps Engineer - Java Developer"
        dates = "October 2018 - March 2020"
        company = "ING Luxembourg"
        details = "Aware of their change and run problems, ING has a big objective of developing their infrastructure and processes. To let teams be more autonomous and manage releases and incidents linked to their assets, ING entrusted me with the creation of an OPS unit and the deployment of the movement. This action is initiated by the Tribe Daily Banking & Lending Engine and extended to all the bank's services. Apart from that, I have been working for a huge migration project at ING Luxembourg that completely refactor the existing payment processing thanks to my Java seniority."
        [[params.experience.list.items]]
        details = "Set up a guild dedicated to the movement, to spread the DevOps culture within ING."
        [[params.experience.list.items]]
        details = "Implementing tools such as Jenkins for packaging, Ansible for infrastructure as code, ELK (Elasticsearch, Logstash, Kibana) for logs aggregation and service liveness."
        [[params.experience.list.items]]
        details = "Evangelization of the DevOps model and implementation of the strategy."
        [[params.experience.list.items]]
        details = "Helping on development of the PSD2 European directive."
        [[params.experience.list.items]]
        details = "Huge migration of the SWIFT payment platform to the ING group payment platform that runs thousands of daily payments."
        

    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Project Lorem Ipsum"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.projects.list]]
        title = "Project Sed Fringilla"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

        [[params.projects.list]]
        title = "Project Praesent"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

    [params.information]
        enable = false

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Climbing, Snowboarding, Photography, Travelling"

    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/MadJlzz"
        title = "MadJlzz"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/klaer-julien"
        title = "Julien Klaer"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "//twitter.com/MadJlzz"
        title = "@MadJlzz"
